Another batch of small improvements
toshima/generalsio pull request #3
Opened 2017-02-03 20:50 UTC by joelthelion

2017-02-03 21:25 UTC, toshima requested changes

2017-02-03 21:25 UTC, toshima commented on generals.py
> +            self._send(["set_force_start", gameid, force_start])
Thanks for the fix! Instead of adding this line, please could you remove the "if gameid:" on line 69?

2017-02-04 13:19 UTC, joelthelion commented on generals.py
> +            self._send(["set_force_start", gameid, force_start])
Done!

2017-02-04 14:56 UTC, merged

2017-02-04 14:56 UTC, toshima commented
Thank you for the fix!