add a new game state
toshima/generalsio pull request #4
Opened 2017-02-04 05:54 UTC by tim-hub

pre game start to logging

2017-02-04 10:58 UTC, toshima requested changes

2017-02-04 10:58 UTC, toshima commented on .gitignore
> +config.py
Thanks for the PR! The change to generals.py is good, but please could you undo the change to .gitignore?

2017-02-05 01:05 UTC, tim-hub commented on .gitignore
> +config.py
yes

2017-02-05 02:38 UTC, tim-hub reviewed
I removed it

2017-02-05 02:38 UTC, tim-hub commented on .gitignore
> +config.py
yes did it. is that ok?

2017-02-05 16:28 UTC, toshima commented
I wanted the line you added to .gitignore to be removed, not the whole file to be deleted.

If you could add back the .gitignore file without the line you added before (config.py), I'd be happy to merge :)

2017-02-06 04:55 UTC, closed without merging